# Generated by Django 2.2.2 on 2019-07-03 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190703_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url_field',
            new_name='link',
        ),
    ]
